//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_WCF_2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWCFMatrix")]
    public interface IWCFMatrix {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFMatrix/CalcDeterminant", ReplyAction="http://tempuri.org/IWCFMatrix/CalcDeterminantResponse")]
        int CalcDeterminant(int[][] refMatrix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFMatrix/CalcDeterminant", ReplyAction="http://tempuri.org/IWCFMatrix/CalcDeterminantResponse")]
        System.Threading.Tasks.Task<int> CalcDeterminantAsync(int[][] refMatrix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFMatrix/FilterAndOrderValues", ReplyAction="http://tempuri.org/IWCFMatrix/FilterAndOrderValuesResponse")]
        string FilterAndOrderValues(int[][] refMatrix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFMatrix/FilterAndOrderValues", ReplyAction="http://tempuri.org/IWCFMatrix/FilterAndOrderValuesResponse")]
        System.Threading.Tasks.Task<string> FilterAndOrderValuesAsync(int[][] refMatrix);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFMatrixChannel : Test_WCF_2.ServiceReference1.IWCFMatrix, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFMatrixClient : System.ServiceModel.ClientBase<Test_WCF_2.ServiceReference1.IWCFMatrix>, Test_WCF_2.ServiceReference1.IWCFMatrix {
        
        public WCFMatrixClient() {
        }
        
        public WCFMatrixClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFMatrixClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFMatrixClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFMatrixClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CalcDeterminant(int[][] refMatrix) {
            return base.Channel.CalcDeterminant(refMatrix);
        }
        
        public System.Threading.Tasks.Task<int> CalcDeterminantAsync(int[][] refMatrix) {
            return base.Channel.CalcDeterminantAsync(refMatrix);
        }
        
        public string FilterAndOrderValues(int[][] refMatrix) {
            return base.Channel.FilterAndOrderValues(refMatrix);
        }
        
        public System.Threading.Tasks.Task<string> FilterAndOrderValuesAsync(int[][] refMatrix) {
            return base.Channel.FilterAndOrderValuesAsync(refMatrix);
        }
    }
}
